apiVersion: v1
kind: Service # mendefinisikan kind adalah service untuk order-service
metadata:
  name: order-service # metadata berupa nama untuk service: order-service
  labels: 
    app: order-service # mendefinisikan label app
spec:
  type: NodePort # menentukan type port adalah nodeport
  ports:
  - port: 3000 # port yang ditentukan untuk service 3000
  selector:
    app: order-service # selector untuk app order-service