apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-1
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: rabbitmq-service
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq 
        selector: rabbitmq-1
    spec:
      containers:
      - name: rabbitmq-container
        image: rabbitmq:3.11-management
        ports:
        - containerPort: 15672 
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /rabbitmq/data
        - name: rabbitmq-log
          mountPath: rabbitmq/log
      volumes:
      - name: rabbitmq-data
        configMap:
          name: rabbitmq-config
          items:
          - key: data.conf
            path: data.conf
      - name: rabbitmq-log
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
      