apiVersion: v1
kind: ConfigMap # mendifinisikan kind adalah configmap
metadata:
  name: rabbitmq-config # metadata nama adalah rabbitmq-config
data:
  data.conf: | # mendefinisikan data dalam configmap untuk mount /rabbitmq/data
    storage:
      data: /rabbitmq/data
