apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: shipping-service 
        image: jefriadisetiawan/shipping-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        env:
        - name: AMQP_URL
          value: "amqp://10.97.235.82:5672"
